const faker = require('faker')
const commonElement = require('../pageObjects/common.js')
const eligibilityfunctionPage = require('../pageObjects/eligibility.js')
const addInvoiceDetailsfunctionPage = require('../pageObjects/addInvoiceDetailsPage.js')

describe('Add Invoice Details', () => {
  it(' 1 Verify happy path - Add Invoice Details', () => {
    // cy.request(

    //   '/set-sysdate?iso-string=2024-08-30T17:48:00.000Z'
    // )
    cy.visit(Cypress.env('baseUrl'))

    cy.fixture('users.json').then((users) => {
      eligibilityfunctionPage.enterIdmUsername(users.email1)
      eligibilityfunctionPage.enterIdmPassword(users.password1)
      commonElement.clickContinueButton()
      cy.wait(3000)
      commonElement.verifyHeaderPage(users.nextpage)
      commonElement.ClickOnNewApplicationButton()
      eligibilityfunctionPage.selectBadgerOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      eligibilityfunctionPage.ClickOnOtherRoleOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      commonElement.GetApplicationTasklist('Add alternative licence holder contact details')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      // cy.get("input[value='new']").click();
      commonElement.clickContinueButton()
      commonElement.SelectYesOptionaOnIsOrganisation()
      commonElement.EnterOrganisationName(faker.company.bs())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.GetApplicationTasklist('Give ecologist details')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get('#contact').click()
      commonElement.clickContinueButton()
      cy.get('#account').click()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.GetApplicationTasklist('Add authorised people')
      // cy.injectAxe()
      // cy.checkA11y(null, { includedImpacts: ['critical', 'serious'] })
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '2, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      //   Add additional contacts
      commonElement.GetApplicationTasklist('Add alternative contacts')
      // cy.injectAxe()
      // cy.checkA11y(null, { includedImpacts: ['critical', 'serious'] })
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get('#new').click()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress().clear()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.GetApplicationTasklist('Add invoice details')
      // cy.injectAxe()
      // cy.checkA11y(null, { includedImpacts: ['critical', 'serious'] })
      addInvoiceDetailsfunctionPage.clickOnIndividualResponsible()
      // cy.get("#responsible").click();
      commonElement.clickContinueButton()
      cy.get('#main-content > div > div').contains(
        'Individual responsible for paying the invoice'
      )
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.enterPurchaseOrderdetails(faker.internet.email())
      // cy.get("#purchase-order").fill(faker.internet.email());
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.Verifypage().contains('COMPLETED')
      addInvoiceDetailsfunctionPage.Verifypage().contains('Add invoice details')
    })
  })
  it(' 1a Verify happy path - Add Invoice Details', () => {
    cy.visit(Cypress.env('baseUrl'))
    cy.fixture('users.json').then((users) => {
      eligibilityfunctionPage.enterIdmUsername(users.email1)
      eligibilityfunctionPage.enterIdmPassword(users.password1)
      commonElement.clickContinueButton()
      cy.wait(3000)
      commonElement.verifyHeaderPage(users.nextpage)
      commonElement.ClickOnNewApplicationButton()
      eligibilityfunctionPage.selectBadgerOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      eligibilityfunctionPage.ClickOnOtherRoleOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.GetApplicationTasklist('Add alternative contacts')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      cy.get("input[value='new']").click()
      commonElement.clickContinueButton()
      commonElement.SelectYesOptionaOnIsOrganisation()
      commonElement.EnterOrganisationName(faker.company.bs())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      cy.get('body > div.govuk-width-container').should('not.have.text', 'e.g. SW1W 0NY')
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.GetApplicationTasklist('Give ecologist details')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get('#contact').click()
      commonElement.clickContinueButton()
      cy.get('#account').click()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.GetApplicationTasklist('Add authorised people')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '2, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      //   Add additional contacts
      commonElement.GetApplicationTasklist('Add alternative contacts')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get('#new').click()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress().clear()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.GetApplicationTasklist('Add invoice details')
      addInvoiceDetailsfunctionPage.clickOnResponsibleTwo()
      // cy.get("#responsible-2").click();
      commonElement.clickContinueButton()
      cy.get('#main-content > div > div').contains(
        'Individual responsible for paying the invoice'
      )
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.clickOnResponsibleFour()
      // cy.get("#responsible-4").click();
      commonElement.clickContinueButton()
      cy.get('body > div.govuk-width-container').contains(
        'Invoice payer details'
      )
      cy.get('body > div.govuk-width-container').contains(
        'You will have to pay a £101 administration charge if you want to change these details after the application is submitted.'
      )
      cy.get('body > div.govuk-width-container').contains(
        'Who should we send the invoice to?'
      )
      cy.get('body > div.govuk-width-container').contains(
        'Enter the full name of an individual. Do not enter the name of an organisation or department.'
      )
      cy.get('body > div.govuk-width-container').contains(
        'Continue'
      )
      cy.get('body > div.govuk-width-container').contains(
        'Back'
      )
      cy.get('#new').click()
      commonElement.clickContinueButton()

      // cy.get("input[value='new']").click()
      //    commonElement.clickContinueButton();
      //     cy.get('#is-organisation').click()
      //     cy.get('#organisation-name').fill(faker.company.bs())
      //    commonElement.clickContinueButton();
      //    commonElement.clickContinueButton();
      //     cy.get('#postcode').fill('M24 6DH')
      //    commonElement.clickContinueButton();
      //     cy.get('#address').select(
      //       '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      //     )
      //    commonElement.clickContinueButton();
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      cy.get("input[value='new']").click()
      commonElement.clickContinueButton()
      commonElement.SelectYesOptionaOnIsOrganisation()
      commonElement.EnterOrganisationName(faker.company.bs())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()

      // commonElement.clickContinueButton();
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.enterPurchaseOrderdetails(faker.internet.email())
      commonElement.clickContinueButton()

      commonElement.clickContinueButton()

      addInvoiceDetailsfunctionPage.Verifypage().contains('COMPLETED')
      addInvoiceDetailsfunctionPage.Verifypage().contains('Add invoice details')
    })
  })

  it(' 2 Verify happy path - Add Invoice Details', () => {
    cy.visit(Cypress.env('baseUrl'))

    cy.fixture('users.json').then((users) => {
      eligibilityfunctionPage.enterIdmUsername(users.email1)
      eligibilityfunctionPage.enterIdmPassword(users.password1)
      commonElement.clickContinueButton()
      cy.wait(3000)
      commonElement.verifyHeaderPage(users.nextpage)
      commonElement.ClickOnNewApplicationButton()
      eligibilityfunctionPage.selectBadgerOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      eligibilityfunctionPage.ClickOnOtherRoleOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      //   Give licence holder details
      commonElement.GetApplicationTasklist('Add alternative contacts')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      cy.get("input[value='new']").click()
      commonElement.clickContinueButton()
      commonElement.SelectYesOptionaOnIsOrganisation()
      commonElement.EnterOrganisationName(faker.company.bs())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      //   Add authorised people
      commonElement.GetApplicationTasklist('Add authorised people')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '2, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()

      //   Give ecologist details

      commonElement.GetApplicationTasklist('Give ecologist details')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get('#contact').click()
      commonElement.clickContinueButton()
      cy.get('#account').click()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Add additional contacts

      commonElement.GetApplicationTasklist('Add alternative contacts')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get("input[value='new']").click()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress().clear()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Add invoice details

      commonElement.GetApplicationTasklist('Add invoice details')
      cy.get("input[value='other']").click()
      commonElement.clickContinueButton()
      cy.get('#new').click()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      cy.get('#account').click()
      commonElement.clickContinueButton()
      cy.get('#change-email').click()
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.enterPurchaseOrderdetails(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.Verifypage().contains('COMPLETED')
      addInvoiceDetailsfunctionPage.Verifypage().contains('Add invoice details')
    })
  })
  it(' 3 Verify happy path - Add Invoice Details', () => {
    cy.visit(Cypress.env('baseUrl'))
    cy.fixture('users.json').then((users) => {
      eligibilityfunctionPage.enterIdmUsername(users.email1)
      eligibilityfunctionPage.enterIdmPassword(users.password1)
      commonElement.clickContinueButton()
      commonElement.verifyHeaderPage(users.nextpage)
      commonElement.ClickOnNewApplicationButton()
      eligibilityfunctionPage.selectBadgerOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Give licence holder details

      commonElement.GetApplicationTasklist('Add alternative contacts')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      cy.get("input[value='new']").click()
      commonElement.clickContinueButton()
      commonElement.SelectYesOptionaOnIsOrganisation()
      commonElement.EnterOrganisationName(faker.company.bs())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Give ecologist details

      commonElement.GetApplicationTasklist('Give ecologist details')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get('#contact').click()
      commonElement.clickContinueButton()
      cy.get('#account').click()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Add authorised people

      commonElement.GetApplicationTasklist('Add authorised people')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '2, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()

      //   Add additional contacts

      commonElement.GetApplicationTasklist('Add alternative contacts')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get("input[value='new']").click()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress().clear()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Add invoice details

      commonElement.GetApplicationTasklist('Add invoice details')
      cy.get("input[value='other']").click()
      commonElement.clickContinueButton()
      cy.get('#new').click()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      cy.get('#account').click()
      commonElement.clickContinueButton()
      commonElement.clickOnChangeEmailOption()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.enterPurchaseOrderdetails(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.Verifypage().contains('COMPLETED')
      addInvoiceDetailsfunctionPage.Verifypage().contains('Add invoice details')
    })
  })

  it(' 4 Verify happy path - Add Invoice Details', () => {
    Cypress.env('baseUrl')
    cy.fixture('users.json').then((users) => {
      eligibilityfunctionPage.enterIdmUsername(users.email1)
      eligibilityfunctionPage.enterIdmPassword(users.password1)
      commonElement.clickContinueButton()
      commonElement.verifyHeaderPage(users.nextpage)
      commonElement.ClickOnNewApplicationButton()
      eligibilityfunctionPage.selectBadgerOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      eligibilityfunctionPage.ClickOnOtherRoleOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Give licence holder details

      commonElement.GetApplicationTasklist('Add alternative contacts')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      cy.get("input[value='new']").click()
      commonElement.clickContinueButton()
      commonElement.SelectYesOptionaOnIsOrganisation()
      commonElement.EnterOrganisationName(faker.company.bs())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Give ecologist details

      commonElement.GetApplicationTasklist('Give ecologist details')
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      cy.get('#contact').click()
      commonElement.clickContinueButton()
      cy.get('#account').click()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()

      //   Add authorised people

      commonElement.GetApplicationTasklist('Add authorised people')
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '2, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      //   Add invoice details
      commonElement.GetApplicationTasklist('Add invoice details')
      cy.get("input[value='other']").click()
      commonElement.clickContinueButton()
      cy.get('#new').click()
      commonElement.clickContinueButton()
      commonElement.EnterName(faker.name.firstName() + ' ' + faker.name.lastName())
      commonElement.clickContinueButton()
      cy.get('#new').click()
      commonElement.clickContinueButton()
      commonElement.SelectYesOptionaOnIsOrganisation()
      commonElement.EnterOrganisationName(faker.company.bs())
      commonElement.clickContinueButton()

      commonElement.EnterEmailAddress(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.EnterPostCode('M24 6DH')
      commonElement.clickContinueButton()
      commonElement.SelectAddress(
        '1, SATIN DRIVE, MIDDLETON, MANCHESTER, M24 6DH'
      )
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.enterPurchaseOrderdetails(faker.internet.email())
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      addInvoiceDetailsfunctionPage.Verifypage().contains('COMPLETED')
      addInvoiceDetailsfunctionPage.Verifypage().contains('Add invoice details')
    })
  })
})
