const faker = require("faker");

describe("Add sett", () => {
  it(" 1 Verify happy path -  Add setts ", () => {
    cy.request(
      Cypress.env("baseUrl") + "set-sysdate?iso-string=2023-04-01T01:00:00.000Z"
    );
  });
  it(" 1 Verify happy path -  Add setts ", () => {
    cy.visit(Cypress.env("baseUrl") + Cypress.env("login"));
    cy.fixture("users.json").then((users) => {
      cy.get("#username").fill(users.email1);
      cy.get("#password").fill(users.password1);
      cy.get("#continue").click();
      cy.get("h1.govuk-fieldset__heading").contains(users.nextpage);
      cy.get("#main-content > div > div > form > fieldset > a").click();
      // cy.get("a.govuk-button").click();
      cy.get("#species").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#yes-no").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("a").contains("Add setts the work will affect").click();
      cy.get("#continue").click();
      cy.get("#habitat-name").fill(faker.random.alphaNumeric(100));
      cy.get("#continue").click();
      cy.get("#habitat-types").click();
      cy.get("#continue").click();
      cy.get("input[value='true']").click();
      cy.get("#continue").click();
      cy.get("#habitat-entrances").fill("7");
      cy.get("#continue").click();
      cy.get("#habitat-active-entrances").fill("5");
      cy.get("#continue").click();
      cy.get("#habitat-grid-ref").fill("NY123456");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-start-day']").fill("1");
      cy.get("input[id='habitat-work-start-month']").fill("05");
      cy.get("input[id='habitat-work-start-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-end-day']").fill("30");
      cy.get("input[id='habitat-work-end-month']").fill("11");
      cy.get("input[id='habitat-work-end-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-activities']").click();
      cy.get("#continue").click();
      cy.get("input[value='yes']").click();
      cy.get("#continue").click();
    });
  });
  it(" 2 Verify happy path -  Add setts ", () => {
    cy.visit(Cypress.env("baseUrl") + Cypress.env("login"));
    cy.fixture("users.json").then((users) => {
      cy.get("#username").fill(users.email1);
      cy.get("#password").fill(users.password1);
      cy.get("#continue").click();
      cy.get("h1.govuk-fieldset__heading").contains(users.nextpage);
      cy.get("#main-content > div > div > form > fieldset > a").click();
      // cy.get("a.govuk-button").click();
      cy.get("#species").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#yes-no").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("a").contains("Add setts the work will affect").click();
      cy.get("#continue").click();
      cy.get("input[id='habitat-name']").fill(faker.random.alphaNumeric(1));
      cy.get("#continue").click();
      cy.get("#habitat-types-2").click();
      cy.get("#continue").click();
      cy.get("input[value='true']").click();
      cy.get("#continue").click();
      cy.get("#habitat-entrances").fill("7");
      cy.get("#continue").click();
      cy.get("#habitat-active-entrances").fill("5");
      cy.get("#continue").click();
      cy.get("#habitat-grid-ref").fill("NY123456");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-start-day']").fill("1");
      cy.get("input[id='habitat-work-start-month']").fill("05");
      cy.get("input[id='habitat-work-start-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-end-day']").fill("30");
      cy.get("input[id='habitat-work-end-month']").fill("11");
      cy.get("input[id='habitat-work-end-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-activities']").click();
      cy.get("#continue").click();
      cy.get("input[value='yes']").click();
      cy.get("#continue").click();
    });
  });
  it(" 3 Verify happy path -  Add setts ", () => {
    // cy.request(Cypress.env("baseUrl") + ('/set-sysdate?iso-string=2023-03-30T17:48:00.000Z'));
    cy.visit(Cypress.env("baseUrl") + Cypress.env("login"));
    cy.fixture("users.json").then((users) => {
      cy.get("#username").fill(users.email1);
      cy.get("#password").fill(users.password1);
      cy.get("#continue").click();
      cy.get("h1.govuk-fieldset__heading").contains(users.nextpage);
      cy.get("#main-content > div > div > form > fieldset > a").click();
      // cy.get("a.govuk-button").click();
      cy.get("#species").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#yes-no").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("a").contains("Add setts the work will affect").click();
      cy.get("#continue").click();
      cy.get("input[id='habitat-name']").fill(faker.random.alphaNumeric(99));
      cy.get("#continue").click();
      cy.get("#habitat-types-3").click();
      cy.get("#continue").click();
      cy.get("input[value='true']").click();
      cy.get("#continue").click();
      cy.get("#habitat-entrances").fill("7");
      cy.get("#continue").click();
      cy.get("#habitat-active-entrances").fill("5");
      cy.get("#continue").click();
      cy.get("#habitat-grid-ref").fill("NY123456");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-start-day']").fill("1");
      cy.get("input[id='habitat-work-start-month']").fill("05");
      cy.get("input[id='habitat-work-start-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-end-day']").fill("30");
      cy.get("input[id='habitat-work-end-month']").fill("11");
      cy.get("input[id='habitat-work-end-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-activities']").click();
      cy.get("#continue").click();
      cy.get("input[value='yes']").click();
      cy.get("#continue").click();
    });
  });
  it("4 Verify happy path -  Add setts ", () => {
    // cy.request(Cypress.env("baseUrl") + ("/set-sysdate?iso-string=2023-05-01T01:01:00.000Z"));
    cy.visit(Cypress.env("baseUrl") + Cypress.env("login"));
    cy.fixture("users.json").then((users) => {
      cy.get("#username").fill(users.email1);
      cy.get("#password").fill(users.password1);
      cy.get("#continue").click();
      cy.get("h1.govuk-fieldset__heading").contains(users.nextpage);
      cy.get("#main-content > div > div > form > fieldset > a").click();
      // cy.get("a.govuk-button").click();
      cy.get("#species").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#yes-no").click();
      cy.get("#continue").click();
      cy.get("#yes-no-2").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("#continue").click();
      cy.get("a").contains("Add setts the work will affect").click();
      cy.get("#continue").click();
      cy.get("#habitat-name").fill(faker.random.alphaNumeric(50));
      cy.get("#continue").click();
      cy.get("#habitat-types-4").click();
      cy.get("#continue").click();
      cy.get("input[value='true']").click();
      cy.get("#continue").click();
      cy.get("#habitat-entrances").fill("7");
      cy.get("#continue").click();
      cy.get("#habitat-active-entrances").fill("5");
      cy.get("#continue").click();
      cy.get("#habitat-grid-ref").fill("NY123456");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-start-day']").fill("1");
      cy.get("input[id='habitat-work-start-month']").fill("05");
      cy.get("input[id='habitat-work-start-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-work-end-day']").fill("30");
      cy.get("input[id='habitat-work-end-month']").fill("11");
      cy.get("input[id='habitat-work-end-year']").fill("2024");
      cy.get("#continue").click();
      cy.get("input[id='habitat-activities']").click();
      cy.get("#continue").click();
      cy.get("input[value='yes']").click();
      cy.get("#continue").click();
    });
  });
});
