const faker = require('faker')
const commonElement = require('../pageObjects/common.js')
const eligibilityfunctionPage = require('../pageObjects/eligibility.js')

describe('Ecologist experience', () => {
  beforeEach(() => {
    cy.visit(Cypress.env('baseUrl'))
    cy.fixture('users.json').then((users) => {
      eligibilityfunctionPage.enterIdmUsername(users.email1)
      eligibilityfunctionPage.enterIdmPassword(users.password1)
      commonElement.clickContinueButton()
      commonElement.verifyHeaderPage(users.nextpage)
      commonElement.ClickOnNewApplicationButton()

      eligibilityfunctionPage.selectBadgerOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      cy.get('#user-role-2').click()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickOnYesOption()
      commonElement.clickContinueButton()
      commonElement.clickOnNoOption()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
      commonElement.clickContinueButton()
    })
  })
  it(' 1 Verify happy path - ecologist experience', () => {
    // Give ecologist’s experience
    commonElement.GetApplicationTasklist('Give ecologist’s experience')
    commonElement.clickOnYesOption()
    commonElement.clickContinueButton()
    cy.get('input#enter-licence-details').fill('NY123456')
    commonElement.clickContinueButton()
    cy.get('#licence-2').click()
    commonElement.clickContinueButton()
    cy.get('#enter-experience').fill(faker.random.alphaNumeric(4000))
    commonElement.clickContinueButton()
    cy.get('#enter-methods').fill(faker.random.alphaNumeric(4000))
    commonElement.clickContinueButton()
    commonElement.clickOnYesOption()
    commonElement.clickContinueButton()
    cy.get('#enter-class-mitigation-details').fill(
      faker.random.alphaNumeric(100)
    )
    commonElement.clickContinueButton()
    commonElement.clickContinueButton()
  })

  it(' 2 Verify happy path - ecologist experience', () => {
    // Give ecologist’s experience
    commonElement.GetApplicationTasklist('Give ecologist’s experience')
    commonElement.clickOnYesOption()
    commonElement.clickContinueButton()
    cy.get('input#enter-licence-details').fill('NY123456')
    commonElement.clickContinueButton()
    cy.get('#licence').click()
    commonElement.clickContinueButton()
    cy.get('input#enter-licence-details').fill('NY123457')
    commonElement.clickContinueButton()
    cy.get('#licence-2').click()
    commonElement.clickContinueButton()
    cy.get('#enter-experience').fill(faker.random.alphaNumeric(40))
    commonElement.clickContinueButton()
    cy.get('#enter-methods').fill(faker.random.alphaNumeric(40))
    commonElement.clickContinueButton()
    commonElement.clickOnYesOption()
    commonElement.clickContinueButton()
    cy.get('#enter-class-mitigation-details').fill('BAD-2022-agsss1')
    commonElement.clickContinueButton()
    commonElement.clickContinueButton()
  })

  it(' 3 Verify happy path - ecologist experience', () => {
    // Give ecologist’s experience
    commonElement.GetApplicationTasklist('Give ecologist’s experience')
    commonElement.clickOnNoOption()
    commonElement.clickContinueButton()
    cy.get('#enter-experience').fill(faker.random.alphaNumeric(40))
    commonElement.clickContinueButton()
    cy.get('#enter-methods').fill(faker.random.alphaNumeric(40))
    commonElement.clickContinueButton()
    commonElement.clickOnNoOption()
    commonElement.clickContinueButton()
    commonElement.clickContinueButton()
  })

  it(' 4 Verify happy path - ecologist experience', () => {
    // Give ecologist’s experience
    commonElement.GetApplicationTasklist('Give ecologist’s experience')
    commonElement.clickOnYesOption()
    commonElement.clickContinueButton()
    cy.get('input#enter-licence-details').fill('NY123456')
    commonElement.clickContinueButton()
    cy.get('#licence-2').click()
    commonElement.clickContinueButton()
    cy.get('#enter-experience').fill(faker.random.alphaNumeric(100))
    commonElement.clickContinueButton()
    cy.get('#enter-methods').fill(faker.random.alphaNumeric(100))
    commonElement.clickContinueButton()
    commonElement.clickOnNoOption()
    commonElement.clickContinueButton()
    commonElement.clickContinueButton()
  })

  it(' 5 Verify happy path - ecologist experience', () => {
    // Give ecologist’s experience

    commonElement.GetApplicationTasklist('Give ecologist’s experience')
    commonElement.clickOnNoOption()
    commonElement.clickContinueButton()
    cy.get('#enter-experience').fill(faker.random.alphaNumeric(400))
    commonElement.clickContinueButton()
    cy.get('#enter-methods').fill(faker.random.alphaNumeric(400))
    commonElement.clickContinueButton()
    commonElement.clickOnYesOption()
    commonElement.clickContinueButton()
    cy.get('#enter-class-mitigation-details').fill('BAD-2022-agsss1')
    commonElement.clickContinueButton()
    commonElement.clickContinueButton()
  })

  it(' 6 Verify happy path - ecologist experience', () => {
    // Give ecologist’s experience
    commonElement.GetApplicationTasklist('Give ecologist’s experience')
    commonElement.clickOnNoOption()
    commonElement.clickContinueButton()
    cy.get('#enter-experience').fill(faker.random.alphaNumeric(10))
    commonElement.clickContinueButton()
    cy.get('#enter-methods').fill(faker.random.alphaNumeric(4001))
    commonElement.clickContinueButton()
    commonElement.VerifyPage('You have entered too many characters')
  })

  it(' 7 Verify happy path - ecologist experience', () => {
    // Give ecologist’s experience

    commonElement.GetApplicationTasklist('Give ecologist’s experience')
    commonElement.clickOnNoOption()
    commonElement.clickContinueButton()
    cy.get('#enter-experience').fill(faker.random.alphaNumeric(4001))
    commonElement.clickContinueButton()
    commonElement.VerifyPage('You have entered too many characters')
  })
})
